### ISSUE TITLE
golang v1.20出来了

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [sbwml/packages_lang_golang#1]
大佬，嘿嘿~~

**Comment by sbwml** [comment]
1

**Comment by sbwml** [comment]
golang 1.20 开始 go bootstrap 需要1.17.3+，这预示着如果纯靠源码编译出最新golang，需要同时编译 1.4、1.17.3+、1.20 这就非常尴尬了。还好办法是靠人想出来的，我直接将prebuilt 1.17.3 作为 bootstrap 去编译 1.20 ，哈哈 直接省去了编译 bootstrap  的耗时。目前只添加了宿主机为 x86_64 的架构，因为我不知道其他系统的arch 显示的是什么，如果是其他系统，直接往这里添加一段即可

https://github.com/sbwml/packages_lang_golang/blob/20.x/golang/Makefile#L72

```
# 比如我使用 armv8 的机器去编译一个openwrt，那就添加这个（虽然用arm编译op的可能性不大，只是个假设参考）
ifeq ($(HOST_ARCH),aarch64)
	PKG_ARCH:=arm64
endif
```

1.20.x 分支

https://github.com/sbwml/packages_lang_golang/tree/20.x
