### ISSUE TITLE
最新版的alist编译要求的golang最低版本已经是1.20了，大佬有时间能升级一下不

### ISSUE THREAD

**Issue by HahahahaChen** [sbwml/packages_lang_golang#2]
![image](https://user-images.githubusercontent.com/42169759/232231092-baeaf72b-5cf3-47f0-8409-9e3c9f48d9f6.png)

**Comment by sbwml** [comment]
https://github.com/sbwml/packages_lang_golang/tree/20.x

切到20.x分支
