### ISSUE TITLE
貌似可以跟官方同步下了

### ISSUE THREAD

**Issue by iamyangyiok** [sbwml/packages_lang_golang#3]
貌似可以跟官方同步更新下了

**Comment by sbwml** [comment]
这玩意我自用有什么好同步的，并且官方的已经是最新

**Comment by iamyangyiok** [comment]
> 这玩意我自用有什么好同步的，并且官方的已经是最新

貌似和OPENWRT官方有差异，我生成说是1.21版，但官方是1.21.4

**Comment by iamyangyiok** [comment]
golang(Directory) | golang: Update to 1.21.4 | last week
-- | -- | --
golang-build.sh(File) | golang: Update to 1.20.6 | 4 months ago
golang-compiler.mk(File) | golang: Update to 1.21.0, remove patch | 3 months ago
golang-host-build.mk(File) | golang: Update to 1.20.6 | 4 months ago
golang-package.mk(File) | golang: Update to 1.21.0, remove patch | 3 months ago
golang-values.mk(File) | golang: Update to 1.21.0, remove patch

**Comment by sbwml** [comment]
openwrt 它是通过全源码编译，版本是1.21.x    

我自己用的这个也是1.21.x   单仅编译一次源码。

发自我的iPhone

**Comment by sbwml** [comment]
我这个主要是用于较老的 sdk 编译需要依赖高版本golang 的插件

发自我的iPhone
